export const commentActionTypes = {
  FETCH_COMMENTS_REQUEST: 'FETCH_COMMENTS_REQUEST',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_FAILURE: 'FETCH_COMMENTS_FAILURE',
  LOAD_MORE_COMMENTS_REQUEST: 'LOAD_MORE_COMMENTS_REQUEST',
  LOAD_MORE_COMMENTS_SUCCESS: 'LOAD_MORE_COMMENTS_SUCCESS',
  LOAD_MORE_COMMENTS_FAILURE: 'LOAD_MORE_COMMENTS_FAILURE',
  TOGGLE_LIKE_COMMENT_REQUEST: 'TOGGLE_LIKE_COMMENT_REQUEST',
  TOGGLE_LIKE_COMMENT_SUCCESS: 'TOGGLE_LIKE_COMMENT_SUCCESS',
  TOGGLE_LIKE_COMMENT_FAILURE: 'TOGGLE_LIKE_COMMENT_FAILURE',
  TOGGLE_LIKE_REPLY_REQUEST: 'TOGGLE_LIKE_REPLY_REQUEST',
  TOGGLE_LIKE_REPLY_SUCCESS: 'TOGGLE_LIKE_REPLY_SUCCESS',
  TOGGLE_LIKE_REPLY_FAILURE: 'TOGGLE_LIKE_REPLY_FAILURE',
  REPLY_COMMENT_REQUEST: 'REPLY_COMMENT_REQUEST',
  REPLY_COMMENT_SUCCESS: 'REPLY_COMMENT_SUCCESS',
  REPLY_COMMENT_FAILURE: 'REPLY_COMMENT_FAILURE',
};

export const LIMIT_COMMENTS_PER_LOADING = 10;
