export const LIMIT_OPPORTUNITY_PER_LOADING = 10;
export const LIMIT_EVENT_PER_LOADING = 10;

export const LIMIT_EVENT_COMMENTS_PER_LOADING = 10;

export const NOTICE_BOARD_LIMIT = 5;

export const eventActionTypes = {
  FETCH_NOTICE_BOARD_REQUEST: 'FETCH_NOTICE_BOARD_REQUEST',
  FETCH_NOTICE_BOARD_SUCCESS: 'FETCH_NOTICE_BOARD_SUCCESS',
  FETCH_NOTICE_BOARD_FAILURE: 'FETCH_NOTICE_BOARD_FAILURE',

  FETCH_EVENT_REQUEST: 'FETCH_EVENT_REQUEST',
  FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
  FETCH_EVENT_FAILURE: 'FETCH_EVENT_FAILURE',

  LOAD_MORE_EVENT_REQUEST: 'LOAD_MORE_EVENT_REQUEST',
  LOAD_MORE_EVENT_SUCCESS: 'LOAD_MORE_EVENT_SUCCESS',
  LOAD_MORE_EVENT_FAILURE: 'LOAD_MORE_EVENT_FAILURE',

  FETCH_OPPORTUNITY_REQUEST: 'FETCH_OPPORTUNITY_REQUEST',
  FETCH_OPPORTUNITY_SUCCESS: 'FETCH_OPPORTUNITY_SUCCESS',
  FETCH_OPPORTUNITY_FAILURE: 'FETCH_OPPORTUNITY_FAILURE',

  LOAD_MORE_OPPORTUNITY_REQUEST: 'LOAD_MORE_OPPORTUNITY_REQUEST',
  LOAD_MORE_OPPORTUNITY_SUCCESS: 'LOAD_MORE_OPPORTUNITY_SUCCESS',
  LOAD_MORE_OPPORTUNITY_FAILURE: 'LOAD_MORE_OPPORTUNITY_FAILURE',

  CEREATE_EVENT_REQUEST: 'CEREATE_EVENT_REQUEST',
  CEREATE_EVENT_SUCCESS: 'CEREATE_EVENT_SUCCESS',
  CEREATE_EVENT_FAILURE: 'CEREATE_EVENT_FAILURE',

  LOAD_EVENT_CALENDAR_REQUEST: 'LOAD_EVENT_CALENDAR_REQUEST',
  LOAD_EVENT_CALENDAR_SUCCESS: 'LOAD_EVENT_CALENDAR_SUCCESS',
  LOAD_EVENT_CALENDAR_FAILURE: 'LOAD_EVENT_CALENDAR_FAILURE',

  EVENT_COMMENT_POST_REQUEST: 'EVENT_COMMENT_POST_REQUEST',
  EVENT_COMMENT_POST_SUCCESS: 'EVENT_COMMENT_POST_SUCCESS',
  EVENT_COMMENT_POST_FAILURE: 'EVENT_COMMENT_POST_FAILURE',

  FETCH_EVENT_COMMENTS_REQUEST: 'FETCH_EVENT_COMMENTS_REQUEST',
  FETCH_EVENT_COMMENTS_SUCCESS: 'FETCH_EVENT_COMMENTS_SUCCESS',
  FETCH_EVENT_COMMENTS_FAILURE: 'FETCH_EVENT_COMMENTS_FAILURE',

  LOAD_MORE_EVENT_COMMENTS_REQUEST: 'LOAD_MORE_EVENT_COMMENTS_REQUEST',
  LOAD_MORE_EVENT_COMMENTS_SUCCESS: 'LOAD_MORE_EVENT_COMMENTS_SUCCESS',
  LOAD_MORE_EVENT_COMMENTS_FAILURE: 'LOAD_MORE_EVENT_COMMENTS_FAILURE',
};
