export const LIMIT_POSTS_PER_LOADING = 10;
export const postActionTypes = {
  FETCH_POST_LIST_REQUEST: 'FETCH_POST_LIST_REQUEST',
  FETCH_POST_LIST_SUCCESS: 'FETCH_POST_LIST_SUCCESS',
  FETCH_POST_LIST_FAILURE: 'FETCH_POST_LIST_FAILURE',
  LOAD_MORE_POST_LIST_REQUEST: 'LOAD_MORE_POST_LIST_REQUEST',
  LOAD_MORE_POST_LIST_SUCCESS: 'LOAD_MORE_POST_LIST_SUCCESS',
  LOAD_MORE_POST_LIST_FAILURE: 'LOAD_MORE_POST_LIST_FAILURE',
  COMMENT_POST_REQUEST: 'COMMENT_POST_REQUEST',
  COMMENT_POST_SUCCESS: 'COMMENT_POST_SUCCESS',
  COMMENT_POST_FAILURE: 'COMMENT_POST_FAILURE',
  TOGGLE_LIKE_POST_REQUEST: 'TOGGLE_LIKE_POST_REQUEST',
  TOGGLE_LIKE_POST_SUCCESS: 'TOGGLE_LIKE_POST_SUCCESS',
  TOGGLE_LIKE_POST_FAILURE: 'TOGGLE_LIKE_POST_FAILURE',
  CREATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
  UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
};
