const images = {
  africaLogo: require('../assets/images/africa-logo.png'),
  sampleLogo: require('../assets/images/sample.jpg'),
  waterLogo: require('../assets/images/water.jpg'),
  flowerLogo: require('../assets/images/flower.jpg'),
  ButterflyLogo: require('../assets/images/Butterfly.jpg'),
  NolithaLogo: require('../assets/images/Nolitha.png'),
  WalusunguLogo: require('../assets/images/Walusungu.png'),
  MphoLogo: require('../assets/images/Mpho.png'),
  membersLogo: require('../assets/images/members.png'),
  members1Logo: require('../assets/images/members1.png'),
  AyandaLogo: require('../assets/images/Ayanda.png'),
  Image4Logo: require('../assets/images/Image4.png'),
  Image5Logo: require('../assets/images/Image5.png'),
  Image6Logo: require('../assets/images/Image6.png'),
  logo1Logo: require('../assets/images/logo1.png'),
  logo2Logo: require('../assets/images/logo2.png'),
  logo3Logo: require('../assets/images/logo3.png'),
  logo4Logo: require('../assets/images/German-AU-logo.png'),
  logo5Logo: require('../assets/images/AGYI.png'),
  logo6Logo: require('../assets/images/wessa.png'),
  logo7Logo: require('../assets/images/african-union.png'),
  welcomeLogo: require('../assets/images/home-back.png'),
  loginLogo: require('../assets/images/login-back.png'),
  Mpho2Logo: require('../assets/images/Mpho2.png'),
  Nolitha2Logo: require('../assets/images/Nolitha2.png'),
};

export default images;
