export const userActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  FETCH_EXTRA_INFO_REQUEST: 'FETCH_EXTRA_INFO_REQUEST',
  FETCH_EXTRA_INFO_SUCCESS: 'FETCH_EXTRA_INFO_SUCCESS',
  FETCH_EXTRA_INFO_FAILURE: 'FETCH_EXTRA_INFO_FAILURE',
  UPDATE_USER_INFO_REQUEST: 'UPDATE_USER_INFO_REQUEST',
  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_INFO_FAILURE: 'UPDATE_USER_INFO_FAILURE',
  UNFOLLOW_REQUEST: 'UNFOLLOW_REQUEST',
  UNFOLLOW_SUCCESS: 'UNFOLLOW_SUCCESS',
  UNFOLLOW_FAILURE: 'UNFOLLOW_FAILURE',
  FOLLOW_REQUEST: 'FOLLOW_REQUEST',
  FOLLOW_SUCCESS: 'FOLLOW_SUCCESS',
  FOLLOW_FAILURE: 'FOLLOW_FAILURE',
  UPDATE_NOTIFICATION_SETTING_REQUEST: 'UPDATE_NOTIFICATION_SETTING_REQUEST',
  UPDATE_NOTIFICATION_SETTING_SUCCESS: 'UPDATE_NOTIFICATION_SETTING_SUCCESS',
  UPDATE_NOTIFICATION_SETTING_FAILURE: 'UPDATE_NOTIFICATION_SETTING_FAILURE',
  UPDATE_PRIVACY_SETTING_REQUEST: 'UPDATE_PRIVACY_SETTING_REQUEST',
  UPDATE_PRIVACY_SETTING_SUCCESS: 'UPDATE_PRIVACY_SETTING_SUCCESS',
  UPDATE_PRIVACY_SETTING_FAILURE: 'UPDATE_PRIVACY_SETTING_FAILURE',
  FETCH_SETTING_REQUEST: 'FETCH_SETTING_REQUEST',
  FETCH_SETTING_SUCCESS: 'FETCH_SETTING_SUCCESS',
  FETCH_SETTING_FAILURE: 'FETCH_SETTING_FAILURE',
  FETCH_RECENT_SEARCH_SUCCESS: 'FETCH_RECENT_SEARCH_SUCCESS',
  UPDATE_EXTRA_INFO_SUCCESS: 'UPDATE_EXTRA_INFO_SUCCESS',
  UPDATE_EXTRA_INFO_FAILURE: 'UPDATE_EXTRA_INFO_FAILURE',
  UPDATE_BOOKMARK_SUCCESS: 'UPDATE_BOOKMARK_SUCCESS',
  UPDATE_BOOKMARK_FAILURE: 'UPDATE_BOOKMARK_FAILURE',
  UPDATE_STORY_ARCHIVE_SUCCESS: 'UPDATE_STORY_ARCHIVE_SUCCESS',
  UPDATE_STORY_ARCHIVE_FAILURE: 'UPDATE_STORY_ARCHIVE_FAILURE',
  UPDATE_POST_ARCHIVE_SUCCESS: 'UPDATE_POST_ARCHIVE_SUCCESS',
  UPDATE_POST_ARCHIVE_FAILURE: 'UPDATE_POST_ARCHIVE_FAILURE',
  FETCH_ARCHIVE_SUCCESS: 'FETCH_ARCHIVE_SUCCESS',
  FETCH_ARCHIVE_FAILURE: 'FETCH_ARCHIVE_FAILURE',
  FETCH_HIGHLIGHT_SUCCESS: 'FETCH_HIGHLIGHT_SUCCESS',
  FETCH_HIGHLIGHT_FAILURE: 'FETCH_HIGHLIGHT_FAILURE',
  UPDATE_HIGHLIGHT_SUCCESS: 'UPDATE_HIGHLIGHT_SUCCESS',
  UPDATE_HIGHLIGHT_FAILURE: 'UPDATE_HIGHLIGHT_FAILURE',
  SET_FCM_TOKEN: 'SET_FCM_TOKEN',
};

export const defaultUserState = {
  user: {},
  photos: [],
  tagPhotos: [],
  taggedPhotos: [],
  bookmarks: [],
  highlights: [],
  archive: {
    stories: [],
    posts: [],
  },
  setting: {
    notification: {
      notificationAccounts: {
        posts: [],
        story: [],
      },
      pauseAll: {
        active: false,
      },
      postStoryComment: {
        likes: 2,
        likesAndCommentOnPhotoOfYou: 2,
        photosOfYou: 1,
        comments: 2,
        commentsAndPins: 1,
        firstPostsAndStories: 1,
      },
      followingFollowers: {
        followerRequest: 1,
        acceptedFollowRequest: 1,
        friendsOnInstagram: 1,
        mentionsInBio: 1,
        recommendationsForOthers: 1,
        recommendationsFromOthers: 1,
      },
      directMessages: {
        messageRequests: 1,
        messages: 1,
        groupRequest: 1,
        videoChats: 2,
      },
      liveIGTV: {
        liveVideos: 1,
        igtvVideoUploads: 1,
        igtvViewCounts: 1,
      },
      fromInstagram: {
        reminders: 1,
        productAnnoucements: 1,
        supportRequests: 1,
      },
      emailAndSMSNotifications: {
        feedbackEmails: true,
        reminderEmails: true,
        productEmail: true,
        newsEmails: true,
        textSMSMessages: true,
      },
    },
    privacy: {
      comments: {
        blockUsers: [],
        filterMostReported: false,
        hideOffensive: true,
        manualFilter: false,
        specificWord: '',
      },
      tags: {
        allowTagFrom: 0,
        manualApproveTags: false,
        pendingTags: [],
      },
      activityStatus: {
        show: true,
      },
      accountPrivacy: {
        private: false,
      },
      story: {
        hideStoryFrom: [],
        allowMessageReplies: 0,
        saveToGallery: true,
        saveToArchive: true,
        allowResharing: false,
        allowSharing: true,
        shareYourStoryToFacebook: false,
      },
      mutedMessages: {
        mutedMessages: [],
      },
      mutedVideoCalls: {
        mutedVideoCalls: [],
      },
      restrictedAccounts: {
        restrictedAccounts: [],
      },
      blockedAccounts: {
        blockedAccounts: [],
      },
      mutedAccouts: {
        posts: [],
        story: [],
      },
      closeFriends: {
        closeFriends: [],
      },
    },
  },
  extraInfo: {
    unSuggestList: [],
    requestedList: [],
    posts: 0,
    followers: [],
    followings: [],
  },
  currentStory: [],
  fcmToken: '',
};
